// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOb8TqVRGWn37PHr4hk-4LGMzJzeRGINQ',
    appId: '1:953859297774:web:402a6e552537aed41ebeff',
    messagingSenderId: '953859297774',
    projectId: 'hangout-4ef39',
    authDomain: 'hangout-4ef39.firebaseapp.com',
    storageBucket: 'hangout-4ef39.firebasestorage.app',
    measurementId: 'G-J9WN1PYD61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUOXW4IKuLH6ZKlWJP7zte3LNbc6edArU',
    appId: '1:953859297774:android:1a6e98ed981375e51ebeff',
    messagingSenderId: '953859297774',
    projectId: 'hangout-4ef39',
    storageBucket: 'hangout-4ef39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcR3tD_6nIR67ce01VJirOSMcbmHY1hvw',
    appId: '1:953859297774:ios:4d06f5c1e4e6456f1ebeff',
    messagingSenderId: '953859297774',
    projectId: 'hangout-4ef39',
    storageBucket: 'hangout-4ef39.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcR3tD_6nIR67ce01VJirOSMcbmHY1hvw',
    appId: '1:953859297774:ios:4d06f5c1e4e6456f1ebeff',
    messagingSenderId: '953859297774',
    projectId: 'hangout-4ef39',
    storageBucket: 'hangout-4ef39.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOb8TqVRGWn37PHr4hk-4LGMzJzeRGINQ',
    appId: '1:953859297774:web:25056be03b047f091ebeff',
    messagingSenderId: '953859297774',
    projectId: 'hangout-4ef39',
    authDomain: 'hangout-4ef39.firebaseapp.com',
    storageBucket: 'hangout-4ef39.firebasestorage.app',
    measurementId: 'G-87V1038T1C',
  );
}
